modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/LogicTechCorp/Reagenchant/issues"
license = "GNU GPLv3"

[[mods]]
modId = "reagenchant"
version = "${file.jarVersion}"
displayName = "Reagenchant"
displayURL = "https://minecraft.curseforge.com/projects/reagenchant"
logoFile = "assets/reagenchant/textures/logo.png"
authors = "LogicTechCorp, Cameron, and misterslime"
description = "A mod that makes enchanting a lot less random."

[[dependencies.reagenchant]]
modId = "abnormals_core"
mandatory = true
versionRange = "[3.1.0,)"
ordering = "AFTER"
side = "BOTH"