modLoader="javafml"
loaderVersion="[31.1,)"
issueTrackerURL="https://github.com/LogicTechCorp/Reagenchant/issues"

[[mods]]
modId="reagenchant"
version="${file.jarVersion}"
displayName="Reagenchant"
displayURL="https://minecraft.curseforge.com/projects/reagenchant"
logoFile="assets/reagenchant/textures/logo.png"
authors="LogicTechCorp, AnarchCassius, LapisWhovian, misterslime, MCvinnyq, and Cameron"
description="A mod that makes enchanting a lot less random."

[[dependencies.reagenchant]]
modId="libraryex"
mandatory=true
versionRange="[3.0.0,)"
ordering="BEFORE"
side="BOTH"