modLoader = "javafml"
loaderVersion = "[28.2,)"
issueTrackerURL = "https://github.com/LogicTechCorp/Reagenchant/issues"

[[mods]]
modId = "reagenchant"
version = "${file.jarVersion}"
displayName = "Reagenchant"
displayURL = "https://minecraft.curseforge.com/projects/reagenchant"
logoFile = "logo.png"
authors = "LogicTechCorp, Cameron, and five."
description = "A mod that makes enchanting a lot less random."

[[dependencies.reagenchant]]
modId = "libraryex"
mandatory = true
versionRange = "[2.0.3,)"
ordering = "BEFORE"
side = "BOTH"